// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_vyK_lbKnV7W5Wl6tdczjBVppa34_FA',
    appId: '1:414026155088:web:da254930af9e8905c33d55',
    messagingSenderId: '414026155088',
    projectId: 'meal-hisab',
    authDomain: 'meal-hisab.firebaseapp.com',
    storageBucket: 'meal-hisab.firebasestorage.app',
    measurementId: 'G-KZZ3NJ7F7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qa4WK1YPFy1EVsWm_2FxBDZCk-2x2OU',
    appId: '1:414026155088:android:fadc4380e57351aac33d55',
    messagingSenderId: '414026155088',
    projectId: 'meal-hisab',
    storageBucket: 'meal-hisab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-p_cKd1lcO8b0EjWrp6Kuzdn2mC-BwZk',
    appId: '1:414026155088:ios:b62e154e7cd4381ac33d55',
    messagingSenderId: '414026155088',
    projectId: 'meal-hisab',
    storageBucket: 'meal-hisab.firebasestorage.app',
    iosBundleId: 'com.example.mealHisab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-p_cKd1lcO8b0EjWrp6Kuzdn2mC-BwZk',
    appId: '1:414026155088:ios:b62e154e7cd4381ac33d55',
    messagingSenderId: '414026155088',
    projectId: 'meal-hisab',
    storageBucket: 'meal-hisab.firebasestorage.app',
    iosBundleId: 'com.example.mealHisab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL_vyK_lbKnV7W5Wl6tdczjBVppa34_FA',
    appId: '1:414026155088:web:c70583cc90c1701ec33d55',
    messagingSenderId: '414026155088',
    projectId: 'meal-hisab',
    authDomain: 'meal-hisab.firebaseapp.com',
    storageBucket: 'meal-hisab.firebasestorage.app',
    measurementId: 'G-DK9CLNBC32',
  );
}
